### ISSUE TITLE
Returning a JSON response - the comment makes the JSON non readable

### ISSUE THREAD

**Issue by kaplandani** [nulab/nginx-length-hiding-filter-module#9] opened 2017-07-09 06:33 UTC
Adding this kind of comment in a JSON response makes most of the service consumer misread the JSON results. Is there a way to make it like a JSON comment  and not HTML comment ?

**Comment by dragon3** [comment] 2017-07-10 12:50
Hi @kaplandani ,
By default, this filter module doesn't add HTML comment if the Content-Type of the response is not "text/html".

Can you show me your configuration?

**Comment by kaplandani** [comment] 2017-07-10 13:28
The content type is Application/json

**Comment by dragon3** [comment] 2017-07-10 13:45
Hi @kaplandani 
I've just tested "application/json" response on my local environment, but I couldn't reproduce your problem.

My nginx.conf is here:
```nginx
user  nginx;
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;

    server {
        listen      80;
        server_name localhost;

        length_hiding on;

        location / {
            root html;
            index index.html;
        }
        location /json {
            default_type application/json;
            return 200 '{"test":"ok"}';
        }
    }
}
```

JSON response doesn't have the HTML comment:
```
$ curl -v localhost:8080/json
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /json HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.12.0
< Date: Mon, 10 Jul 2017 13:43:01 GMT
< Content-Type: application/json
< Content-Length: 13
< Connection: keep-alive
<
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
{"test":"ok"}
```

HTML response has the comment:
```
$ curl -v localhost:8080/
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET / HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.12.0
< Date: Mon, 10 Jul 2017 13:44:17 GMT
< Content-Type: text/html
< Content-Length: 1800
< Last-Modified: Mon, 10 Jul 2017 13:39:29 GMT
< Connection: keep-alive
< ETag: "59638391-264"
<
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
* Curl_http_done: called premature == 0
* Connection #0 to host localhost left intact
<!-- random-length HTML comment: o1QeNuD9YGLwCglyvjjJesov3Uvie99I0PkB7o8VuKFvophYOGhsxLdqdMO8JLE8Yp7WR6pBGvusaRGoYlULvvzO8BKFNPDj4B5L5lK9U5ruMyWiZqrKbgZXgjbtweQqdMzYvAXF3FxF1JmQxTZMywiST9BGdPu5bkTKipPbsAejJGx4YMHK8pcSobYFqI8IqQQO5epleKKmQ5gmIlwGQOW2ps6W12cfIsuBMXmphuRwqvYwXJ2lXNcB5YXuQxQXd8YoV9T1tinXT9JqIAQeNsfIE01SnHpGFCuYBBPsj2G30Ph6Pxaaf3hhtY0WfdbifJ4gLKPuATl0iJxw4LMYFt5wHvHkPiGsrBN2JalJtMAPTvBO4Mm73fu9R1heXoKEnX5wxe3go3w8mvMf7wczRKyg9VAW7JZigSSUwMyaDiYqUiJPUjEku0GtMFEHOdqut8CfK13OZQ2rw97Fi9pQ0v8AyCHCdxvMuxp2mgEAu4ph3mmakPqa8oYxofzFRkR9W416Z46JymoqMOGuduIcXgPBCCHRlWQ7PH3oByvyYaekokVISdip8vrAxwRYGfTTmL5m9raXH25taO1sqXYoIDo4x3Q1YkL8tGisx6D2y8mOLb71xTf5WHxJ8EAUmJQVQzBBtC2iAcuL3pAq8fkUmVbiXa29hJSv6RxpTnLSF6b8lcnk7L2igSE4s71NEI9AZwnrXz9cvaYW094yKvUpDYhtTY6Ve5V4p7jCwich611xyuj9f1mgPJPhhL2AFM2uJbv59La3APqz7PwaGY6UhLzCVrCY14GAVz3SBRMBf00cGm3KAxcf7RiQ7ioyduxwkqDl6PmbFb1JDsSCguhdAFt7mVtFFgznL2MHFxgLOXSPGiRkRxBR0sMcD5hGcVunN6sTrOc5lsLpRaNiNOxE69g72CEUXw5iqn1Y1TTbCcER1SxCekEbhjWZlas6Mne3RUPGnihn9m2y2p0WN5vueIIDi09tdbksvzzXVU8S41Gwe7Js24cWCkZjaWQ2v0khnX26syPmpTZKQi2GaSad1xAPJQH5EqapDQlvEyYsIv0WRsdr83IzpIDyYKra0FF2VrnYd9Gls689mZpiQxW56ZsShZtWdwOwdzK5xOgfIcfszKPG5l918rIfFzzilBU -->
```

**Comment by dragon3** [comment] 2017-07-11 13:09
Hi @kaplandani ,
I'm going to close this issue, but if you still have the problem please comment here.

Thank you!

**Closed as completed by dragon3** 2017-07-11 13:09 UTC
